CREATE TABLE tb_game
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255),
    game_year         INTEGER,
    genre             VARCHAR(255),
    platforms         VARCHAR(255),
    score             DOUBLE PRECISION,
    img_url           VARCHAR(255),
    short_description TEXT,
    long_description  TEXT,
    CONSTRAINT pk_tb_game PRIMARY KEY (id)
);